[2024-04-04T12:15:18.416+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: conrad_coding_test.task_2_spark manual__2024-04-04T12:14:09.723413+00:00 [queued]>
[2024-04-04T12:15:18.422+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: conrad_coding_test.task_2_spark manual__2024-04-04T12:14:09.723413+00:00 [queued]>
[2024-04-04T12:15:18.423+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-04-04T12:15:18.439+0000] {taskinstance.py:2217} INFO - Executing <Task(DockerOperator): task_2_spark> on 2024-04-04 12:14:09.723413+00:00
[2024-04-04T12:15:18.447+0000] {standard_task_runner.py:60} INFO - Started process 145661 to run task
[2024-04-04T12:15:18.454+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'conrad_coding_test', 'task_2_spark', 'manual__2024-04-04T12:14:09.723413+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dag_spark_multi_source_test_docker.py', '--cfg-path', '/tmp/tmpbsp1o47c']
[2024-04-04T12:15:18.457+0000] {standard_task_runner.py:88} INFO - Job 24: Subtask task_2_spark
[2024-04-04T12:15:18.517+0000] {task_command.py:423} INFO - Running <TaskInstance: conrad_coding_test.task_2_spark manual__2024-04-04T12:14:09.723413+00:00 [running]> on host de-zoomcamp.us-central1-a.c.my-zhe-414813.internal
[2024-04-04T12:15:18.591+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='conrad_coding_test' AIRFLOW_CTX_TASK_ID='task_2_spark' AIRFLOW_CTX_EXECUTION_DATE='2024-04-04T12:14:09.723413+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-04T12:14:09.723413+00:00'
[2024-04-04T12:15:18.651+0000] {docker.py:359} INFO - Starting docker container from image sparkhome:latest
[2024-04-04T12:15:19.209+0000] {docker.py:429} INFO - Unsetting extraneous env vars (UTC): 12:15:19
[2024-04-04T12:15:19.210+0000] {docker.py:429} INFO - Finished unsetting extraneous env vars (UTC): 12:15:19
[2024-04-04T12:15:19.211+0000] {docker.py:429} INFO - ++ id -u
[2024-04-04T12:15:19.214+0000] {docker.py:429} INFO - + myuid=0
[2024-04-04T12:15:19.214+0000] {docker.py:429} INFO - ++ id -g
[2024-04-04T12:15:19.216+0000] {docker.py:429} INFO - + mygid=0
[2024-04-04T12:15:19.216+0000] {docker.py:429} INFO - + set +e
[2024-04-04T12:15:19.217+0000] {docker.py:429} INFO - ++ getent passwd 0
[2024-04-04T12:15:19.219+0000] {docker.py:429} INFO - + uidentry=root:x:0:0:root:/root:/bin/bash
[2024-04-04T12:15:19.219+0000] {docker.py:429} INFO - + set -e
[2024-04-04T12:15:19.222+0000] {docker.py:429} INFO - + '[' -z root:x:0:0:root:/root:/bin/bash ']'
+ SPARK_CLASSPATH=':/opt/spark/jars/*'
[2024-04-04T12:15:19.222+0000] {docker.py:429} INFO - + env
+ sort -t_ -k4 -n
[2024-04-04T12:15:19.223+0000] {docker.py:429} INFO - + grep SPARK_JAVA_OPT_
[2024-04-04T12:15:19.224+0000] {docker.py:429} INFO - + sed 's/[^=]*=\(.*\)/\1/g'
[2024-04-04T12:15:19.227+0000] {docker.py:429} INFO - + readarray -t SPARK_EXECUTOR_JAVA_OPTS
[2024-04-04T12:15:19.227+0000] {docker.py:429} INFO - + '[' -n '' ']'
+ '[' -z ']'
+ '[' -z ']'
+ '[' -n '' ']'
+ '[' -z ']'
[2024-04-04T12:15:19.228+0000] {docker.py:429} INFO - + '[' -z ']'
[2024-04-04T12:15:19.228+0000] {docker.py:429} INFO - + '[' -z x ']'
[2024-04-04T12:15:19.228+0000] {docker.py:429} INFO - + SPARK_CLASSPATH='/opt/spark/conf::/opt/spark/jars/*'
[2024-04-04T12:15:19.229+0000] {docker.py:429} INFO - Non-spark-on-k8s command provided, proceeding in pass-through mode...
[2024-04-04T12:15:19.229+0000] {docker.py:429} INFO - + case "$1" in
+ echo 'Non-spark-on-k8s command provided, proceeding in pass-through mode...'
+ CMD=("$@")
+ exec /usr/bin/tini -s -- python /opt/spark/etl_task_2.py
[2024-04-04T12:15:22.321+0000] {docker.py:429} INFO - WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark/jars/spark-unsafe_2.12-3.2.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[2024-04-04T12:15:22.321+0000] {docker.py:429} INFO - 
[2024-04-04T12:15:23.223+0000] {docker.py:429} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2024-04-04T12:15:23.223+0000] {docker.py:429} INFO - Setting default log level to "
[2024-04-04T12:15:23.223+0000] {docker.py:429} INFO - WARN
[2024-04-04T12:15:23.224+0000] {docker.py:429} INFO - ".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2024-04-04T12:15:23.633+0000] {docker.py:429} INFO - 24/04/04 12:15:23 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-04-04T12:15:30.414+0000] {docker.py:429} INFO - Traceback (most recent call last):
  File "/opt/spark/etl_task_2.py", line 24, in <module>
    df_1_users = spark.read.option("header", "true").csv('/opt/spark/mount_data/users.csv')
  File "/opt/conda/lib/python3.8/site-packages/pyspark/sql/readwriter.py", line 410, in csv
    return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
  File "/opt/conda/lib/python3.8/site-packages/py4j/java_gateway.py", line 1321, in __call__
    return_value = get_return_value(
  File "/opt/conda/lib/python3.8/site-packages/pyspark/sql/utils.py", line 117, in deco
    raise converted from None
pyspark.sql.utils.AnalysisException: Path does not exist: file:/opt/spark/mount_data/users.csv
[2024-04-04T12:15:30.782+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/datatalks_jan/anaconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/datatalks_jan/anaconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/datatalks_jan/anaconda3/lib/python3.11/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/datatalks_jan/anaconda3/lib/python3.11/site-packages/airflow/providers/docker/operators/docker.py", line 364, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/datatalks_jan/anaconda3/lib/python3.11/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2024-04-04T12:15:30.787+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=conrad_coding_test, task_id=task_2_spark, execution_date=20240404T121409, start_date=20240404T121518, end_date=20240404T121530
[2024-04-04T12:15:30.801+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 24 for task task_2_spark (Docker container failed: {'StatusCode': 1}; 145661)
[2024-04-04T12:15:30.814+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-04T12:15:30.835+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
